name = "fantasy-cricket-api"
account_id = "c986632a81b447fffc4caeea39130869"
main = "workers/index.js"
compatibility_date = "2024-01-01"

[vars]
RAPID_API_KEY = "70a8792460msh629f8e0af8cc36bp17accbjsn7c270b8814ee"
RAPID_API_HOST = "unofficial-cricbuzz.p.rapidapi.com"

# Firestore configuration
FIREBASE_PROJECT_ID = "axevora11"
FIREBASE_API_KEY = "AIzaSyDVoZoy6_Qz36Xz3P7CbkGSB75Vq0CsJhU"

# Cashfree Configuration (Backend Only)
# CASHFREE_APP_ID = "YOUR_APP_ID"
# CASHFREE_SECRET_KEY = "YOUR_SECRET_KEY"
# CASHFREE_IS_SANDBOX = "false"
WORKER_URL = "https://fantasy-cricket-api.moremagical4.workers.dev"

[[d1_databases]]
binding = "DB"
database_name = "cricbuzz_d1_prod"
database_id = "118ed0ed-c0c5-44ce-bae7-783876d95878"

[triggers]
crons = ["*/5 * * * *"]
