import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:axevora11/features/chat/domain/chat_message_model.dart';
import 'package:axevora11/features/user/presentation/providers/user_provider.dart';

final chatMessagesProvider = StreamProvider.family<List<ChatMessage>, String>((ref, matchId) {
  return FirebaseFirestore.instance
      .collection('matches')
      .doc(matchId)
      .collection('chats')
      .orderBy('timestamp', descending: true)
      .limit(50)
      .snapshots()
      .map((snapshot) {
        return snapshot.docs
            .map((doc) => ChatMessage.fromMap(doc.data(), doc.id))
            .toList();
      });
});

final chatServiceProvider = Provider((ref) => ChatService(ref));

class ChatService {
  final Ref _ref;
  final FirebaseFirestore _firestore = FirebaseFirestore.instance;

  ChatService(this._ref);

  Future<void> sendMessage(String matchId, String text, {Map<String, dynamic>? scoreSnip}) async {
    final userAsync = _ref.read(userEntityProvider);
    final user = userAsync.value;
    if (user == null) return;

    final message = ChatMessage(
      id: '', // Will be generated by Firestore
      senderId: user.uid,
      senderName: user.displayName ?? 'Player',
      senderPhoto: user.photoUrl ?? '',
      text: text,
      timestamp: DateTime.now(),
      scoreSnip: scoreSnip,
    );

    await _firestore
        .collection('matches')
        .doc(matchId)
        .collection('chats')
        .add(message.toMap());
  }
}
